apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.name" . }}-configmap
data:
  application.yaml: |
    external.identity.url: "http://{{ include "identity.name" . }}:8181/v1"
    external.naming.url: "http://{{ include "naming.name" . }}:8182/v1"
