apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.name" . }}
  labels:
    app: {{ include "api-gateway.name" . }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ include "api-gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-gateway.name" . }}
    spec:
      serviceAccountName: {{ .Release.Name }}-basic
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ include "api-gateway.name" . }}
          image: mckulpa/k8s-demo-api-gateway:1.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/app/config/application.yaml"
          volumeMounts:
            - name: {{ include "api-gateway.name" . }}-config-volume
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              cpu: 600m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 1
      volumes:
        - name: {{ include "api-gateway.name" . }}-config-volume
          configMap:
            name: {{ include "api-gateway.name" . }}-configmap
            items:
              - key: application.yaml
                path: application.yaml
