apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "api-gateway.name" . }}
  ports:
    - port: 8180
      targetPort: http
