apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: api-gateway-pod
          image: mckulpa/k8s-demo-api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EXTERNAL_IDENTITY_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-configmap
                  key: IDENTITY_URL
            - name: EXTERNAL_NAMING_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-configmap
                  key: NAMING_URL
