apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
data:
  application.yaml: |
    server.port: {{ .Values.containerPort | quote }}
    external.identity.url: "http://identity-clusterip:8181/v1"
    external.naming.url: "http://naming-clusterip:8182/v1"
