apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: basic
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-gateway-pod
          image: mckulpa/k8s-demo-api-gateway:1.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/app/config/application.yaml"
          volumeMounts:
            - name: api-gateway-config-volume
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              cpu: 600m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 1
      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-configmap
            items:
              - key: application.yaml
                path: application.yaml
