apiVersion: v1
kind: Service
metadata:
  name: {{ include "naming.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "naming.name" . }}
  ports:
    - port: 8182
      targetPort: http
