apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "identity.name" . }}
  ports:
    - port: 8181
      targetPort: http
