apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: basic
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
      terminationGracePeriodSeconds: 30
      startupProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 12
      readinessProbe:
        httpGet:
          path: /ready
          port: http
        periodSeconds: 10
        failureThreshold: 1
      livenessProbe:
        httpGet:
          path: /health
          port: http
        periodSeconds: 10
        failureThreshold: 1
      containers:
        - name: api-gateway-pod
          image: mckulpa/k8s-demo-api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "/app/config/application.yaml"
          volumeMounts:
            - name: api-gateway-config-volume
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-configmap
            items:
              - key: application.yaml
                path: application.yaml
