apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deploy
  labels:
    app: identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: identity-pod
          image: mckulpa/k8s-demo-identity:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
