apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-deploy
  labels:
    app: naming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naming
  template:
    metadata:
      labels:
        app: naming
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: naming-pod
          image: mckulpa/k8s-demo-naming:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
